### PR TITLE
Exposing option to json encode or not

### PR DESCRIPTION
**Pull request by JoshKoberstein**
My framework has output functionality that handles the json encoding.  I would like to add the ability to json_encode or not to the public marshall function so I do not have to decode the json only to encode the json again.  Thank you!  This is a great library - exactly what I was looking for!

### CODE REVIEW

**Comment by AnujRNair** [comment]
Hey @JoshKoberstein, thanks for the PR!

Would you be able to provide a code sample for where this is useful - I'm not sure I understand your requirements? I haven't generally seen anyone using the marshall function to only turn a class into an assoc array - the function is only really useful to turn the class into an actual JSON string, given that is what the library is built to do :)

Thanks!

**Comment by JoshKoberstein** [comment]
Hi!  My project has the following methods and I route all my responses through them:

```
  public function respondData($data, $statusCode = 200) {
    return $this->respondJson([
      'success' => true,
      'data' => $data
    ], $statusCode);
  }

  public function respondJson($data, $statusCode = 200) {
    return response()->json($data)
      ->setStatusCode($statusCode);
  }
```

response()->json($data) expects an array ( see:  https://github.com/laravel/framework/blob/5.3/src/Illuminate/Http/JsonResponse.php ).

So, I must json_decode the marshalled string so that it can be passed to JsonResponse and re-encoded there.  I just figured it would be a good option to be able to not encode the string to prevent unnecessary overhead ( be it a tiny overhead ).

**Comment by AnujRNair** [comment]
Sounds good to me! PR merged

**Comment by JoshKoberstein** [comment]
Thank you!

**Pull request merged**
